# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 05a3164f41782c6f778eadfa80edb7e9d976a77c27feaedbe34b610d0df36504ec9e51d89b0681274ce71934e9ed96113ca510856e9bb36ba8dd2f1664c9f740

test:
  secret_key_base: 1fb8e6222a6156fd88e8781892ba33b0179412771282e5b08b8d0df90efdf4ff5b0e1cbe08421f8709fa1bae4b851c81ada08b15fb48468d4fc9caf1245d17eb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
